---
- name: Install nginx with vhosts
  hosts: webservers
  become: true
  become_method: sudo
  gather_facts: no

  vars:
    sites:
      - "fiz.com"
      - "meh.com"
      - "bio.com"

  roles:
  - nginx_vhosts
